# -*- coding: utf-8 -*-
"""A Forest of Trees(sololearn).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ussNgK01XoDSxHN0D3EyGBUJAhSrxO5r
"""

#Importing libraries 
import numpy as np #Numpy for array transformation
#Importing Random forest algo for model 

from sklearn.ensemble import RandomForestClassifier

#For training and testing the model

from sklearn.model_selection import train_test_split

#Model inputs
randomstate = int(input())
n = int(input())
rows = []
for i in range(n):
    rows.append([float(a) for a in input().split()])

X = np.array(rows)
y = np.array([int(a) for a in input().split()])

#Spliting the X and y into train test splits
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=randomstate)

#Genrating the random forest model 
model_rf=RandomForestClassifier(n_estimators=5,random_state=randomstate)#Esitmator is 5
model_rf.fit(X_train,y_train)#fitting the X_train and y_train
print(model_rf.predict(X_test))#Predicting the X_test